version: "3.8"

services:
  nginx:
    ports:
      - "3000:80"

  node-docker3:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
    - node_modules:/app/node_modules
    - ./:/app
    environment:
      - NODE_ENV=development
      - MONGO_USER=shabbir
      - MONGO_PASSWORD=mypassword
      - SESSION_SECRET=secret
    command: npm run dev

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=shabbir
      - MONGO_INITDB_ROOT_PASSWORD=mypassword

volumes:
  node_modules:
